In [1]:
import numpy as np
ar=np.arange(100)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [20]:
data=np.random.randn(3,2)
print(data)

[[ 0.82879726  0.8435764 ]
 [-0.16909942  0.62525017]
 [ 0.97775588 -0.9446416 ]]


In [3]:
data * 10
data + data

array([[-0.85621689,  1.74802131],
       [-1.41666379,  1.14296884],
       [ 3.66467242, -0.06945008]])

In [4]:
print(data.shape)
print(data.dtype)

(3, 2)
float64


In [5]:
data = [[1,2,3,4],[5,6,7,8]]
arr=np.array(data)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
element_present = any(i == 5 for i in data) 
print(element_present)


False


In [10]:
specific_element=data[0][1] 
print(specific_element)

2


In [11]:
ar=np.array([1,2,3,4,5])
ar1=ar.astype(np.int64)
print(ar1)


[1 2 3 4 5]


In [19]:
sliced_data1=data[:2] 
sliced_data = data[0][:2]
print(sliced_data)
print(sliced_data1)

[1, 2]
[[1, 2, 3, 4], [5, 6, 7, 8]]
